name: Dana Silver
markdown: redcarpet
pygments: true
exclude: ['less', '.gitignore', '*.sublime-*', 'README.md']

permalink: pretty

splash_imgs: ['/static/imgs/splash/tetons_short.jpg', '/static/imgs/splash/bikeburl_short.jpg']